### ISSUE TITLE
Code in documentation no longer compiles

### ISSUE THREAD

**Issue by blast-hardcheese** [endpoints4s/endpoints4s#208]
I'm having a difficult time getting started with endpoints as the example code doesn't compile with the latest release (0.7.0).

Copy-pasting http://julienrf.github.io/endpoints/quick-start.html into an otherwise empty file yields:
```
[error] .../src/main/scala/.../client/HttpClient.scala:28:18: polymorphic expression cannot be instantiated to expected type;
[error]  found   : [UrlAndBodyPTupled]CounterEndpoints.this.Request[tuplerABC.Out]
[error]  required: CounterEndpoints.this.Request[Increment]
[error] Error occurred in an application involving default arguments.
[error]     endpoint(post(path / "increment", jsonRequest[Increment]()), emptyResponse())
[error]                  ^
[error] .../src/main/scala/.../client/HttpClient.scala:50:20: type JsonSchemaEntities is not a member of package endpoints.xhr.circe
[error]     with xhr.circe.JsonSchemaEntities
[error]                    ^
[error] two errors found
```

Altering the `endpoint(post(...` to
```scala
    endpoint(post[Unit, Increment, Unit, Increment](path / "increment", jsonRequest[Increment]()), emptyResponse())
```

resolves that compiler error; I'm using `-Ypartial-unification` and `-Xexperimental` with 2.12.6, so I'm not sure where to go from here. I'd expect extraordinarily specific types to be required if I had a nontrivial number of parameters, so this isn't really practical even as a stopgap.

As for the `JsonSchemaEntities` error, I'm not really getting the significance between `JsonSchemaEntities` and `JsonEntities` and `JsonEntities`, so any changes to attempt and resolve this error have just been guesses.
