### PR TITLE
Add JsonEntitiesFromEncodersAndDecoders in http4s

### PR DESCRIPTION
**Pull request by mleclercq**
Addresses https://github.com/endpoints4s/endpoints4s/issues/585

### CODE REVIEW

**Review by julienrf — COMMENTED** [review]
Thank you @mleclercq!

It seems that the code does not compile on Scala 2.12: https://travis-ci.com/github/endpoints4s/endpoints4s/jobs/459005085#L594-L608

**Review by julienrf — APPROVED** [review]

**Comment by mleclercq** [comment]
I've fixed the 2.12 compilation errors. I'm not sure why it can't figure out the implicits. So instead I passed/used the `endpoints.Effect` explicitly. This is not pretty but it works 😉

**Comment by julienrf** [comment]
Thank you!
